version: '3.8'

services:
  zookeeper:
    image: 'registry.cn-shenzhen.aliyuncs.com/colovu/zookeeper:3.6'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_LISTEN_ALLIPS_ENABLED=yes

  # 宿主机中其他应用直接访问时，需要确保宿主机hosts中已经包含kafka1定义
  kafka1:
    image: 'registry.cn-shenzhen.aliyuncs.com/colovu/kafka:2.5'
    ports:
      - '9092:9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL://:9193,CLIENT://kafka1:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://:9193,CLIENT://kafka1:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper

  # 宿主机中其他应用直接访问时，需要确保宿主机hosts中已经包含kafka2定义
  kafka2:
    image: 'registry.cn-shenzhen.aliyuncs.com/colovu/kafka:2.5'
    ports:
      - '9093:9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=2
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL://:9193,CLIENT://kafka2:9093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://:9193,CLIENT://kafka2:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper

  # 宿主机中其他应用直接访问时，需要确保宿主机hosts中已经包含kafka3定义
  kafka3:
    image: 'registry.cn-shenzhen.aliyuncs.com/colovu/kafka:2.5'
    ports:
      - '9094:9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=3
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL://:9193,CLIENT://kafka3:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://:9193,CLIENT://kafka3:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper
