version: '3.6'

services:
  zoo1:
    image: 'colovu/zookeeper:latest'
    container_name: zoo1
    ports:
      - 2181:2181
    environment:
      - ZOO_ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_LISTEN_ALLIPS_ENABLED=yes

  kafka1:
    image: 'colovu/kafka:latest'
    ports:
      - '9092:9092'
      - '9193:9193'
    container_name: kafka1
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL://:9193,CLIENT://kafka1:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://:9193,CLIENT://kafka1:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zoo1

  kafka2:
    image: 'colovu/kafka:latest'
    ports:
      - '9093:9092'
      - '9194:9193'
    container_name: kafka2
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181
      - KAFKA_BROKER_ID=2
      - KAFKA_ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL://:9193,CLIENT://kafka2:9093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://:9193,CLIENT://kafka2:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zoo1

  kafka3:
    image: 'colovu/kafka:latest'
    ports:
      - '9094:9092'
      - '9195:9193'
    container_name: kafka3
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181
      - KAFKA_BROKER_ID=3
      - KAFKA_ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL://:9193,CLIENT://kafka3:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://:9193,CLIENT://kafka3:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zoo1
